# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'pg8583client'
  version: 0.0.1
servers:
  - url: http://localhost:21016
    description: Development server
  - url: https://localhost:21016
    description: Development server with TLS Profile
paths: {}
